### PR TITLE
serialize/deserialize function inputs

### PR DESCRIPTION
**Pull request by glennmoy**
Building off #23

### CODE REVIEW

**Comment by glennmoy** [comment]
adding a second test to `task.jl` hangs...I presume this is the deadlocking issue we saw before?

even so, testing on just the integer case errors when `take!`ing the data...

```julia
Submit task: Error During Test at /Users/glenn/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/task.jl:1
  Got exception outside of a @test
  C++ object of type N3ray6BufferE was deleted
  Stacktrace:
    [1] Data(arg1::Union{ray_core_worker_julia_jll.Buffer, CxxWrap.CxxWrapCore.ConstCxxRef{<:ray_core_worker_julia_jll.Buffer}, CxxWrap.CxxWrapCore.CxxRef{<:ray_core_worker_julia_jll.Buffer}})
      @ ray_core_worker_julia_jll ~/.julia/packages/CxxWrap/aXNBY/src/CxxWrap.jl:624
    [2] take!(buffer::CxxWrap.CxxWrapCore.SmartPointer{<:ray_core_worker_julia_jll.Buffer})
      @ ray_core_worker_julia_jll ~/.julia/dev/ray_core_worker_julia_jll/src/wrappers/any.jl:138
    [3] macro expansion
      @ ~/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/task.jl:8 [inlined]
    [4] macro expansion
      @ /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Test/src/Test.jl:1498 [inlined]
    [5] top-level scope
      @ ~/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/task.jl:7
    [6] include
      @ ./client.jl:478 [inlined]
    [7] #4
      @ ~/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/runtests.jl:21 [inlined]
    [8] setup_core_worker(body::var"#4#6")
      @ Main ~/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/utils.jl:19
    [9] #3
      @ ~/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/runtests.jl:20 [inlined]
   [10] setup_ray_head_node(body::var"#3#5")
      @ Main ~/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/utils.jl:10
   [11] macro expansion
      @ ~/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/runtests.jl:18 [inlined]
   [12] macro expansion
      @ /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Test/src/Test.jl:1498 [inlined]
   [13] top-level scope
      @ ~/.julia/dev/ray_core_worker_julia_jll/Ray.jl/test/runtests.jl:14
   [14] include(fname::String)
      @ Base.MainInclude ./client.jl:478
   [15] top-level scope
      @ none:6
   [16] eval
      @ ./boot.jl:370 [inlined]
   [17] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:280
   [18] _start()
      @ Base ./client.jl:522
```

**Comment by kleinschmidt** [comment]
> adding a second test to task.jl hangs...I presume this is the deadlocking issue we saw before

yeah sounds like it :-/   seems like this is going to become blocking very soon

**Comment by kleinschmidt** [comment]
> testing on just the integer case errors when take!ing the data...

I was seeing that same error when the worker failed for some reason.  if you're testing locally, have a look at `raylet.err`

**Comment by glennmoy** [comment]
> > testing on just the integer case errors when take!ing the data...
> 
> I was seeing that same error when the worker failed for some reason. if you're testing locally, have a look at `raylet.err`

ah it was a mess up on my side `ERROR: MethodError: no method matching sum(::Int64, ::Int64, ::Int64)`

**Review by kleinschmidt — APPROVED** [review]
I think this looks good.   agree with the TODO.

**Pull request merged**
